In [1]:
pip install MetaTrader5

Requirement already satisfied: MetaTrader5 in c:\users\chunwaichi\documents\python_projects\installation\venv\lib\site-packages (5.0.45)
Requirement already satisfied: numpy>=1.7 in c:\users\chunwaichi\documents\python_projects\installation\venv\lib\site-packages (from MetaTrader5) (1.26.2)
Note: you may need to restart the kernel to use updated packages.

TypeError: 'str' object is not callable

In [26]:
from datetime import datetime
import matplotlib.pyplot as plt
import pandas as pd
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
import MetaTrader5 as mt5
 
# connect to MetaTrader 5
if not mt5.initialize():
    print("initialize() failed")
    mt5.shutdown()

login =51499008
password="iPijcvdF"
server="ICMarketsSC-Demo"
mt5.login(login,password,server)

True

In [30]:
rates=mt5.copy_rates_from("XAUUSD",mt5.TIMEFRAME_D1,datetime.now(),100)

In [31]:
rates

array([(1689033600, 1925.19, 1938.45, 1924.38, 1932.09, 72793, 0, 0),
       (1689120000, 1932.31, 1959.67, 1932.26, 1957.35, 79435, 0, 0),
       (1689206400, 1957.04, 1963.58, 1952.43, 1960.39, 81084, 0, 0),
       (1689292800, 1960.27, 1963.77, 1950.95, 1955.45, 79557, 0, 0),
       (1689552000, 1955.42, 1959.9 , 1945.78, 1954.92, 69205, 0, 0),
       (1689638400, 1954.69, 1984.42, 1954.61, 1978.73, 81400, 0, 0),
       (1689724800, 1978.88, 1980.91, 1969.77, 1976.97, 72285, 0, 0),
       (1689811200, 1976.56, 1987.46, 1965.38, 1969.5 , 79625, 0, 0),
       (1689897600, 1970.39, 1973.8 , 1956.86, 1961.84, 73394, 0, 0),
       (1690156800, 1962.1 , 1967.91, 1953.4 , 1954.87, 70532, 0, 0),
       (1690243200, 1955.28, 1965.67, 1952.5 , 1964.85, 66193, 0, 0),
       (1690329600, 1964.98, 1978.41, 1962.  , 1972.27, 80852, 0, 0),
       (1690416000, 1971.51, 1982.2 , 1942.62, 1945.52, 81964, 0, 0),
       (1690502400, 1946.59, 1963.58, 1945.38, 1959.15, 86490, 0, 0),
       (1690761600, 1959.57, 1972.42, 1951.31, 1965.52, 69456, 0, 0),
       (1690848000, 1965.78, 1966.05, 1941.27, 1944.19, 68912, 0, 0),
       (1690934400, 1950.77, 1954.78, 1933.04, 1934.87, 75256, 0, 0),
       (1691020800, 1935.42, 1939.  , 1929.55, 1933.98, 73735, 0, 0),
       (1691107200, 1934.67, 1946.76, 1925.68, 1942.65, 73275, 0, 0),
       (1691366400, 1942.55, 1946.71, 1931.53, 1936.52, 58701, 0, 0),
       (1691452800, 1936.2 , 1938.08, 1922.78, 1925.22, 69623, 0, 0),
       (1691539200, 1925.07, 1932.39, 1914.07, 1914.7 , 62137, 0, 0),
       (1691625600, 1914.81, 1930.15, 1912.17, 1912.33, 72903, 0, 0),
       (1691712000, 1912.41, 1920.92, 1910.8 , 1913.62, 62865, 5, 0),
       (1691971200, 1912.52, 1916.2 , 1902.74, 1907.42, 66807, 5, 0),
       (1692057600, 1907.19, 1911.64, 1896.36, 1901.85, 79160, 2, 0),
       (1692144000, 1901.12, 1907.2 , 1891.84, 1891.92, 71791, 5, 0),
       (1692230400, 1891.93, 1903.44, 1885.04, 1889.33, 76422, 0, 0),
       (1692316800, 1889.25, 1896.84, 1886.8 , 1889.37, 67024, 5, 0),
       (1692576000, 1889.08, 1898.78, 1884.86, 1894.67, 71421, 4, 0),
       (1692662400, 1894.52, 1904.47, 1889.16, 1897.38, 70291, 5, 0),
       (1692748800, 1897.46, 1920.38, 1897.17, 1915.38, 74417, 5, 0),
       (1692835200, 1915.14, 1923.35, 1911.81, 1916.69, 72480, 5, 0),
       (1692921600, 1916.92, 1922.36, 1903.8 , 1914.21, 70507, 5, 0),
       (1693180800, 1915.31, 1926.08, 1912.84, 1920.06, 60328, 5, 0),
       (1693267200, 1919.78, 1938.15, 1914.46, 1937.32, 68437, 0, 0),
       (1693353600, 1937.55, 1949.1 , 1934.97, 1942.42, 73188, 4, 0),
       (1693440000, 1942.55, 1947.83, 1939.01, 1940.06, 66446, 0, 0),
       (1693526400, 1939.88, 1952.91, 1934.44, 1939.85, 70753, 0, 0),
       (1693785600, 1940.34, 1946.36, 1936.79, 1938.58, 41239, 2, 0),
       (1693872000, 1938.4 , 1938.97, 1925.36, 1925.97, 69986, 4, 0),
       (1693958400, 1926.  , 1929.18, 1915.31, 1916.42, 66585, 4, 0),
       (1694044800, 1916.6 , 1923.58, 1916.26, 1919.62, 60469, 4, 0),
       (1694131200, 1919.38, 1929.71, 1917.34, 1919.13, 60460, 4, 0),
       (1694390400, 1919.83, 1930.73, 1916.8 , 1922.33, 69102, 4, 0),
       (1694476800, 1922.74, 1924.5 , 1907.64, 1913.34, 61103, 0, 0),
       (1694563200, 1912.77, 1915.71, 1905.59, 1908.15, 67736, 5, 0),
       (1694649600, 1908.54, 1912.88, 1901.  , 1910.51, 73098, 5, 0),
       (1694736000, 1910.77, 1930.39, 1909.8 , 1923.68, 70372, 5, 0),
       (1694995200, 1923.77, 1934.23, 1922.57, 1933.61, 60352, 4, 0),
       (1695081600, 1933.44, 1937.41, 1929.81, 1931.34, 51241, 4, 0),
       (1695168000, 1931.62, 1947.42, 1927.95, 1930.36, 65021, 0, 0),
       (1695254400, 1930.78, 1931.59, 1913.94, 1919.94, 68600, 3, 0),
       (1695340800, 1919.88, 1929.1 , 1919.44, 1925.25, 55851, 5, 0),
       (1695600000, 1924.76, 1927.16, 1915.16, 1915.78, 50930, 4, 0),
       (1695686400, 1916.04, 1916.81, 1899.12, 1900.58, 56212, 4, 0),
       (1695772800, 1900.38, 1903.9 , 1872.54, 1874.99, 64525, 0, 0),
       (1695859200, 1876.04, 1879.53, 1857.68, 1864.8 , 71401, 4, 0),
       (1695945600, 1865.24, 1879.84, 1846.32, 1848.74, 71290, 2, 0),
       (1696204800, 1847.81, 1850.59, 1827.14, 1827.77, 73721, 2, 0),
       (1696291200, 1828.8 , 1833.36, 1815.32, 1822.94, 84475, 2, 0),
       (1696377600, 1822.84, 1830.51, 1816.64, 1821.1 , 84955, 1, 0),
       (1696464000, 1821.53, 1829.2 , 1813.07, 1820.24, 72504, 0, 0),
       (1696550400, 1820.26, 1834.88, 1810.43, 1831.84, 79020, 0, 0),
       (1696809600, 1848.06, 1863.5 , 1844.23, 1861.35, 72162, 2, 0),
       (1696896000, 1861.1 , 1865.4 , 1853.  , 1860.42, 79376, 4, 0),
       (1696982400, 1859.76, 1877.18, 1858.63, 1874.27, 79764, 3, 0),
       (1697068800, 1874.56, 1884.95, 1867.89, 1868.73, 80778, 5, 0),
       (1697155200, 1868.85, 1932.41, 1868.7 , 1932.41, 91680, 0, 0),
       (1697414400, 1929.58, 1929.58, 1908.18, 1920.06, 83605, 5, 0),
       (1697500800, 1919.7 , 1931.56, 1912.41, 1923.05, 82134, 5, 0),
       (1697587200, 1923.36, 1962.6 , 1923.24, 1947.62, 91821, 0, 0),
       (1697673600, 1947.5 , 1977.72, 1945.25, 1974.28, 97368, 2, 0),
       (1697760000, 1974.09, 1997.17, 1972.02, 1980.9 , 98585, 0, 0),
       (1698019200, 1965.68, 1982.82, 1964.38, 1972.74, 91603, 0, 0),
       (1698105600, 1972.68, 1980.83, 1953.59, 1971.03, 87458, 5, 0),
       (1698192000, 1971.38, 1987.24, 1963.05, 1979.45, 82466, 0, 0),
       (1698278400, 1980.79, 1993.45, 1971.86, 1984.73, 92691, 1, 0),
       (1698364800, 1984.51, 2009.36, 1976.88, 2005.91, 91397, 0, 0),
       (1698624000, 2004.22, 2006.82, 1990.92, 1996.15, 88959, 0, 0),
       (1698710400, 1995.58, 2007.89, 1978.88, 1983.97, 86603, 2, 0),
       (1698796800, 1983.8 , 1992.02, 1969.88, 1982.67, 89782, 0, 0),
       (1698883200, 1983.25, 1991.03, 1978.85, 1985.77, 77763, 0, 0),
       (1698969600, 1985.28, 2004.09, 1983.28, 1992.52, 81103, 0, 0),
       (1699228800, 1992.4 , 1993.14, 1977.4 , 1977.82, 76594, 0, 0),
       (1699315200, 1977.83, 1978.36, 1956.68, 1969.03, 82055, 3, 0),
       (1699401600, 1968.77, 1971.06, 1947.44, 1950.2 , 79831, 1, 0),
       (1699488000, 1950.  , 1965.58, 1944.64, 1958.41, 83073, 0, 0),
       (1699574400, 1958.3 , 1960.82, 1933.04, 1938.62, 82411, 0, 0),
       (1699833600, 1938.57, 1949.2 , 1931.72, 1946.1 , 76526, 2, 0),
       (1699920000, 1946.17, 1970.89, 1943.81, 1963.16, 78038, 0, 0),
       (1700006400, 1962.58, 1975.1 , 1955.44, 1959.19, 84975, 0, 0),
       (1700092800, 1960.08, 1987.96, 1956.52, 1981.1 , 78654, 1, 0),
       (1700179200, 1980.86, 1993.42, 1978.64, 1980.56, 80147, 5, 0),
       (1700438400, 1978.25, 1985.25, 1965.42, 1977.65, 91348, 4, 0),
       (1700524800, 1977.91, 2007.57, 1977.71, 1998.26, 95942, 0, 0),
       (1700611200, 1998.88, 2006.24, 1986.91, 1989.81, 86320, 0, 0),
       (1700697600, 1989.18, 1998.51, 1989.12, 1992.74, 43763, 0, 0),
       (1700784000, 1992.98, 2003.67, 1991.45, 2002.44, 58798, 0, 0),
       (1701043200, 2002.4 , 2018.19, 2000.64, 2013.62, 22532, 0, 0)],
      dtype=[('time', '<i8'), ('open', '<f8'), ('high', '<f8'), ('low', '<f8'), ('close', '<f8'), ('tick_volume', '<u8'), ('spread', '<i4'), ('real_volume', '<u8')])

In [32]:
account_info = mt5.account_info()

In [34]:
account_info.balance

10000.0

In [35]:
num_symbols=mt5.symbols_total()

In [36]:
num_symbols

2137

In [37]:
mt5.symbol_info("XAUUSD")._asdict()

{'custom': False,
 'chart_mode': 0,
 'select': True,
 'visible': False,
 'session_deals': 0,
 'session_buy_orders': 0,
 'session_sell_orders': 0,
 'volume': 0,
 'volumehigh': 0,
 'volumelow': 0,
 'time': 1701069619,
 'digits': 2,
 'spread': 0,
 'spread_float': True,
 'ticks_bookdepth': 10,
 'trade_calc_mode': 0,
 'trade_mode': 4,
 'start_time': 0,
 'expiration_time': 0,
 'trade_stops_level': 0,
 'trade_freeze_level': 0,
 'trade_exemode': 2,
 'swap_mode': 1,
 'swap_rollover3days': 3,
 'margin_hedged_use_leg': False,
 'expiration_mode': 15,
 'filling_mode': 2,
 'order_mode': 127,
 'order_gtc_mode': 0,
 'option_mode': 0,
 'option_right': 0,
 'bid': 2013.59,
 'bidhigh': 2018.19,
 'bidlow': 2000.64,
 'ask': 2013.59,
 'askhigh': 2018.26,
 'asklow': 2000.64,
 'last': 0.0,
 'lasthigh': 0.0,
 'lastlow': 0.0,
 'volume_real': 0.0,
 'volumehigh_real': 0.0,
 'volumelow_real': 0.0,
 'option_strike': 0.0,
 'point': 0.01,
 'trade_tick_value': 1.0,
 'trade_tick_value_profit': 1.0,
 'trade_tick_value_loss': 1.0,
 'trade_tick_size': 0.01,
 'trade_contract_size': 100.0,
 'trade_accrued_interest': 0.0,
 'trade_face_value': 0.0,
 'trade_liquidity_rate': 0.0,
 'volume_min': 0.01,
 'volume_max': 100.0,
 'volume_step': 0.01,
 'volume_limit': 0.0,
 'swap_long': -32.84,
 'swap_short': 20.78,
 'margin_initial': 100.0,
 'margin_maintenance': 0.0,
 'session_volume': 0.0,
 'session_turnover': 0.0,
 'session_interest': 0.0,
 'session_buy_orders_volume': 0.0,
 'session_sell_orders_volume': 0.0,
 'session_open': 2002.4,
 'session_close': 2002.48,
 'session_aw': 0.0,
 'session_price_settlement': 0.0,
 'session_price_limit_min': 0.0,
 'session_price_limit_max': 0.0,
 'margin_hedged': 100.0,
 'price_change': 0.5548,
 'price_volatility': 0.0,
 'price_theoretical': 0.0,
 'price_greeks_delta': 0.0,
 'price_greeks_theta': 0.0,
 'price_greeks_gamma': 0.0,
 'price_greeks_vega': 0.0,
 'price_greeks_rho': 0.0,
 'price_greeks_omega': 0.0,
 'price_sensitivity': 0.0,
 'basis': '',
 'category': '',
 'currency_base': 'XAU',
 'currency_profit': 'USD',
 'currency_margin': 'XAU',
 'bank': '',
 'description': 'Gold vs US Dollar',
 'exchange': '',
 'formula': '',
 'isin': '',
 'name': 'XAUUSD',
 'page': '',
 'path': 'Commodities\\Metals\\XAUUSD'}

In [38]:
import pandas as pd

In [59]:
ohlc= pd.DataFrame(mt5.copy_rates_from("XAUUSD", mt5.TIMEFRAME_M1,datetime(year=2023,month=11,day=1),10000))
ohlc

,time,open,high,low,close,tick_volume,spread,real_volume
0,1698027120,1977.16,1978.19,1976.90,1977.89,39,8,0
1,1698027180,1977.87,1977.93,1977.34,1977.39,21,8,0
2,1698027240,1977.39,1977.66,1977.39,1977.55,18,7,0
3,1698027300,1977.55,1977.55,1977.09,1977.44,28,8,0
4,1698027360,1977.54,1977.71,1977.45,1977.71,11,5,0
...,...,...,...,...,...,...,...,...
9995,1698825360,1977.36,1977.69,1977.34,1977.69,21,5,0
9996,1698825420,1977.69,1977.83,1977.65,1977.76,33,5,0
9997,1698825480,1977.76,1977.91,1977.66,1977.83,37,5,0
9998,1698825540,1977.83,1977.83,1977.51,1977.67,31,5,0
9999,1698825600,1977.62,1977.62,1977.18,1977.31,30,6,0

In [60]:
ohlc["time"] = pd.to_datetime(ohlc["time"],unit='s')

In [61]:
ohlc

,time,open,high,low,close,tick_volume,spread,real_volume
0,2023-10-23 02:12:00,1977.16,1978.19,1976.90,1977.89,39,8,0
1,2023-10-23 02:13:00,1977.87,1977.93,1977.34,1977.39,21,8,0
2,2023-10-23 02:14:00,1977.39,1977.66,1977.39,1977.55,18,7,0
3,2023-10-23 02:15:00,1977.55,1977.55,1977.09,1977.44,28,8,0
4,2023-10-23 02:16:00,1977.54,1977.71,1977.45,1977.71,11,5,0
...,...,...,...,...,...,...,...,...
9995,2023-11-01 07:56:00,1977.36,1977.69,1977.34,1977.69,21,5,0
9996,2023-11-01 07:57:00,1977.69,1977.83,1977.65,1977.76,33,5,0
9997,2023-11-01 07:58:00,1977.76,1977.91,1977.66,1977.83,37,5,0
9998,2023-11-01 07:59:00,1977.83,1977.83,1977.51,1977.67,31,5,0
9999,2023-11-01 08:00:00,1977.62,1977.62,1977.18,1977.31,30,6,0

In [65]:
import plotly.express as px 
import nbformat
fig = px.line(ohlc,x = ohlc["time"], y=ohlc['close'])
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed